import type { OptionDef } from './types';

/**
 * 선택지 낱개 풀.
 *
 * 예전에는 이벤트 하나가 두 선택지를 상황 문구로 묶고 있었다. 그런데 플레이어가
 * 실제로 판단하는 것은 "이 둘이 서로 어떤 관계인가"이고, 그 관계는 저작 시점에
 * 고정돼 있어 비율을 맞출 수 없었다 (대립 31% / 동류 67% / 위기 2%).
 *
 * 그래서 선택지를 낱개로 풀어 태그만 붙여 두고, 짝은 pairing.ts가 매번
 * 규칙에 맞게 조합한다. 문구는 짝을 모르는 채로도 홀로 서야 하므로 전부
 * 스스로 설명하는 형태다.
 *
 * 태그
 * - `axis`  무엇을 만지는가: 덱 / 필드 / 뽑기 / 체력
 * - `dir`   미래(덱 구성)인가 현재(필드·체력)인가 — 대립 짝을 가르는 축
 * - `value` 플레이어에게 돌아오는 이득의 크기. "유혹의 세기"다
 * - `rarity` 등장 가중치
 * - `crisis` 이득이 없고 손해만 있는 선택지. 위기 짝 전용 풀
 */
export const OPTION_POOL: OptionDef[] = [
  {
    id: 'forge-red',
    text: '중립 2장을 녹여 보상 1장으로 벼린다',
    tone: 'sure',
    axis: 'deck',
    dir: 'future',
    value: 'low',
    rarity: 'common',
    effects: [{ type: 'transform', from: 'neutral', to: 'reward', count: 2 }],
  },
  {
    id: 'forge-blue',
    text: '보상 1장, 저주 1장, 값싼 2장을 값으로',
    tone: 'greed',
    axis: 'deck',
    dir: 'future',
    value: 'low',
    rarity: 'common',
    effects: [{ type: 'addRandom', kind: 'reward', count: 1 }, { type: 'addRandom', kind: 'curse', count: 1 }, { type: 'removeExtreme', end: 'lowest', count: 2 }],
  },
  {
    id: 'crack-1-red',
    text: '파편을 뜯어낸다 — 파편 1, 저주 2장, 값싼 2장이 부서진다',
    tone: 'now',
    axis: 'deck',
    dir: 'future',
    value: 'high',
    rarity: 'ultra',
    effects: [{ type: 'shard', count: 1 }, { type: 'addRandom', kind: 'curse', count: 2 }, { type: 'removeExtreme', end: 'lowest', count: 2 }],
  },
  {
    id: 'crack-1-blue',
    text: '덱에서 2장을 펼친다 — 덱의 중립 1장을 잃는다',
    tone: 'later',
    axis: 'draw',
    dir: 'now',
    value: 'low',
    rarity: 'common',
    effects: [{ type: 'drawField', count: 2 }, { type: 'removeKind', kind: 'neutral', count: 1 }],
  },
  {
    id: 'collector-red',
    text: '가장 값나가는 것을 판다 — 그 자리에 보상 2장',
    tone: 'gamble',
    axis: 'deck',
    dir: 'future',
    value: 'mid',
    rarity: 'uncommon',
    effects: [{ type: 'removeExtreme', end: 'highest', count: 1 }, { type: 'addRandom', kind: 'reward', count: 2 }],
  },
  {
    id: 'collector-blue',
    text: '값싼 2장을 버리고 보상 1장',
    tone: 'sure',
    axis: 'deck',
    dir: 'future',
    value: 'low',
    rarity: 'common',
    effects: [{ type: 'removeExtreme', end: 'lowest', count: 2 }, { type: 'addRandom', kind: 'reward', count: 1 }],
  },
  {
    id: 'debt-red',
    text: '저주가 3장 이상이면 보상 2장, 아니면 저주 1장',
    tone: 'gamble',
    axis: 'deck',
    dir: 'future',
    value: 'mid',
    rarity: 'uncommon',
    effects: [{ type: 'ifThen', when: { type: 'countAtLeast', kind: 'curse', n: 3 }, then: [{ type: 'addRandom', kind: 'reward', count: 2 }], otherwise: [{ type: 'addRandom', kind: 'curse', count: 1 }] }],
  },
  {
    id: 'debt-blue',
    text: '보상 1장을 두고 온다',
    tone: 'safe',
    axis: 'deck',
    dir: 'future',
    value: 'low',
    rarity: 'common',
    effects: [{ type: 'removeKind', kind: 'reward', count: 1 }],
  },
  {
    id: 'crack-2-red',
    text: '기어들어 파편을 캔다 — 파편 1, 저주 2장, 보상 1장을 흘린다',
    tone: 'now',
    axis: 'deck',
    dir: 'future',
    value: 'high',
    rarity: 'ultra',
    effects: [{ type: 'shard', count: 1 }, { type: 'addRandom', kind: 'curse', count: 2 }, { type: 'removeKind', kind: 'reward', count: 1 }],
  },
  {
    id: 'crack-2-blue',
    text: '저주 2장을 묻고 잔해에서 중립 1장을 줍는다',
    tone: 'later',
    axis: 'deck',
    dir: 'future',
    value: 'high',
    rarity: 'rare',
    effects: [{ type: 'removeKind', kind: 'curse', count: 2 }, { type: 'addRandom', kind: 'neutral', count: 1 }],
  },
  {
    id: 'alchemist-red',
    text: '저주 2장을 보상으로 바꾼다 — 중립 1장을 촉매로 태운다',
    tone: 'sure',
    axis: 'deck',
    dir: 'future',
    value: 'high',
    rarity: 'rare',
    effects: [{ type: 'transform', from: 'curse', to: 'reward', count: 2 }, { type: 'removeKind', kind: 'neutral', count: 1 }],
  },
  {
    id: 'alchemist-blue',
    text: '중립 3장을 저주로 바꾸고 보상 2장을 받는다 — 값싼 1장이 삭는다',
    tone: 'gamble',
    axis: 'deck',
    dir: 'future',
    value: 'mid',
    rarity: 'uncommon',
    effects: [{ type: 'transform', from: 'neutral', to: 'curse', count: 3 }, { type: 'addRandom', kind: 'reward', count: 2 }, { type: 'removeExtreme', end: 'lowest', count: 1 }],
  },
  {
    id: 'hoard-red',
    text: '덱이 14장 이상이면 값싼 4장을 버린다, 아니면 중립 1장을 받는다',
    tone: 'safe',
    axis: 'deck',
    dir: 'future',
    value: 'low',
    rarity: 'common',
    effects: [{ type: 'ifThen', when: { type: 'deckAtLeast', n: 14 }, then: [{ type: 'removeExtreme', end: 'lowest', count: 4 }], otherwise: [{ type: 'addRandom', kind: 'neutral', count: 1 }] }],
  },
  {
    id: 'hoard-blue',
    text: '보상 2장, 저주 1장, 값싼 2장을 떨군다',
    tone: 'greed',
    axis: 'deck',
    dir: 'future',
    value: 'mid',
    rarity: 'uncommon',
    effects: [{ type: 'addRandom', kind: 'reward', count: 2 }, { type: 'addRandom', kind: 'curse', count: 1 }, { type: 'removeExtreme', end: 'lowest', count: 2 }],
  },
  {
    id: 'crack-3-red',
    text: '파편 2개를 한 번에 뜯는다 — 저주 3장, 값싼 3장이 무너진다',
    tone: 'now',
    axis: 'deck',
    dir: 'future',
    value: 'high',
    rarity: 'ultra',
    effects: [{ type: 'shard', count: 2 }, { type: 'addRandom', kind: 'curse', count: 3 }, { type: 'removeExtreme', end: 'lowest', count: 3 }],
  },
  {
    id: 'crack-3-blue',
    text: '저주 1장을 걷어내고 보상 1장',
    tone: 'later',
    axis: 'deck',
    dir: 'future',
    value: 'mid',
    rarity: 'uncommon',
    effects: [{ type: 'removeKind', kind: 'curse', count: 1 }, { type: 'addRandom', kind: 'reward', count: 1 }],
  },
  {
    id: 'gambler-red',
    text: '보상이 4장 이상이면 보상 1장 더, 아니면 값싼 2장을 잃는다',
    tone: 'gamble',
    axis: 'deck',
    dir: 'future',
    value: 'low',
    rarity: 'common',
    effects: [{ type: 'ifThen', when: { type: 'countAtLeast', kind: 'reward', n: 4 }, then: [{ type: 'addRandom', kind: 'reward', count: 1 }], otherwise: [{ type: 'removeExtreme', end: 'lowest', count: 2 }] }],
  },
  {
    id: 'gambler-blue',
    text: '중립 2장을 쥐고, 값나가는 1장을 판돈으로',
    tone: 'sure',
    axis: 'deck',
    dir: 'future',
    value: 'low',
    rarity: 'common',
    effects: [{ type: 'addRandom', kind: 'neutral', count: 2 }, { type: 'removeExtreme', end: 'highest', count: 1 }],
  },
  {
    id: 'crack-4-red',
    text: '파편 1, 저주 2장, 중립 2장이 떨어져 나간다',
    tone: 'now',
    axis: 'deck',
    dir: 'future',
    value: 'high',
    rarity: 'ultra',
    effects: [{ type: 'shard', count: 1 }, { type: 'addRandom', kind: 'curse', count: 2 }, { type: 'removeKind', kind: 'neutral', count: 2 }],
  },
  {
    id: 'crack-4-blue',
    text: '보상 1장, 저주 1장, 값싼 1장을 흘린다',
    tone: 'later',
    axis: 'deck',
    dir: 'future',
    value: 'low',
    rarity: 'common',
    effects: [{ type: 'addRandom', kind: 'reward', count: 1 }, { type: 'addRandom', kind: 'curse', count: 1 }, { type: 'removeExtreme', end: 'lowest', count: 1 }],
  },
  {
    id: 'mirror-red',
    text: '중립이 2장 이하면 보상 1장, 아니면 중립이 전부 저주가 된다',
    tone: 'gamble',
    axis: 'deck',
    dir: 'future',
    value: 'low',
    rarity: 'common',
    effects: [{ type: 'ifThen', when: { type: 'countAtMost', kind: 'neutral', n: 2 }, then: [{ type: 'addRandom', kind: 'reward', count: 1 }], otherwise: [{ type: 'transform', from: 'neutral', to: 'curse', count: 99 }] }],
  },
  {
    id: 'mirror-blue',
    text: '저주 1장, 값싼 1장을 버린다',
    tone: 'safe',
    axis: 'deck',
    dir: 'future',
    value: 'low',
    rarity: 'common',
    effects: [{ type: 'addRandom', kind: 'curse', count: 1 }, { type: 'removeExtreme', end: 'lowest', count: 1 }],
  },
  {
    id: 'crack-5-red',
    text: '파편을 뽑는다 — 파편 1, 저주가 4장 미만이면 저주 3장, 아니면 보상 1장',
    tone: 'now',
    axis: 'deck',
    dir: 'future',
    value: 'high',
    rarity: 'ultra',
    effects: [{ type: 'shard', count: 1 }, { type: 'removeExtreme', end: 'lowest', count: 2 }, { type: 'ifThen', when: { type: 'countAtMost', kind: 'curse', n: 3 }, then: [{ type: 'addRandom', kind: 'curse', count: 3 }], otherwise: [{ type: 'addRandom', kind: 'reward', count: 1 }] }],
  },
  {
    id: 'crack-5-blue',
    text: '저주 2장을 지우고 보상 1장을 잃는다',
    tone: 'later',
    axis: 'deck',
    dir: 'future',
    value: 'high',
    rarity: 'rare',
    effects: [{ type: 'removeKind', kind: 'curse', count: 2 }, { type: 'removeKind', kind: 'reward', count: 1 }],
  },
  {
    id: 'toll-red',
    text: '덱이 10장 이하면 보상 1장, 아니면 값싼 3장을 잃는다',
    tone: 'gamble',
    axis: 'deck',
    dir: 'future',
    value: 'low',
    rarity: 'common',
    effects: [{ type: 'ifThen', when: { type: 'deckAtMost', n: 10 }, then: [{ type: 'addRandom', kind: 'reward', count: 1 }], otherwise: [{ type: 'removeExtreme', end: 'lowest', count: 3 }] }],
  },
  {
    id: 'toll-blue',
    text: '저주 1장, 중립 1장을 잃는다',
    tone: 'sure',
    axis: 'deck',
    dir: 'future',
    value: 'low',
    rarity: 'common',
    effects: [{ type: 'addRandom', kind: 'curse', count: 1 }, { type: 'removeKind', kind: 'neutral', count: 1 }],
  },
  {
    id: 'crack-6-red',
    text: '파편 1, 저주 2장, 보상 2장을 대가로',
    tone: 'now',
    axis: 'deck',
    dir: 'future',
    value: 'high',
    rarity: 'ultra',
    effects: [{ type: 'shard', count: 1 }, { type: 'addRandom', kind: 'curse', count: 2 }, { type: 'removeKind', kind: 'reward', count: 2 }],
  },
  {
    id: 'crack-6-blue',
    text: '보상 2장, 저주 1장, 값싼 2장을 흘린다',
    tone: 'later',
    axis: 'deck',
    dir: 'future',
    value: 'mid',
    rarity: 'uncommon',
    effects: [{ type: 'addRandom', kind: 'reward', count: 2 }, { type: 'addRandom', kind: 'curse', count: 1 }, { type: 'removeExtreme', end: 'lowest', count: 2 }],
  },
  {
    id: 'gate-red',
    text: '덱에서 3장을 필드에 펼친다 — 겹치면 그 자리에서 터진다',
    tone: 'gamble',
    axis: 'draw',
    dir: 'now',
    value: 'low',
    rarity: 'common',
    effects: [{ type: 'drawField', count: 3 }],
  },
  {
    id: 'gate-blue',
    text: '값싼 3장을 버린다',
    tone: 'safe',
    axis: 'deck',
    dir: 'future',
    value: 'low',
    rarity: 'common',
    effects: [{ type: 'removeExtreme', end: 'lowest', count: 3 }],
  },
  {
    id: 'miasma-red',
    text: '덱에서 4장을 필드에 펼친다 — 겹치면 그 자리에서 터진다',
    tone: 'now',
    axis: 'draw',
    dir: 'now',
    value: 'low',
    rarity: 'common',
    effects: [{ type: 'drawField', count: 4 }],
  },
  {
    id: 'miasma-blue',
    text: '덱에서 2장을 펼친다 — 덱의 값싼 2장을 흘린다',
    tone: 'later',
    axis: 'draw',
    dir: 'now',
    value: 'low',
    rarity: 'common',
    effects: [{ type: 'drawField', count: 2 }, { type: 'removeExtreme', end: 'lowest', count: 2 }],
  },
  {
    id: 'trial-red',
    text: '덱에서 2장을 필드에 펼친다 — 겹치면 그 자리에서 터진다',
    tone: 'sure',
    axis: 'draw',
    dir: 'now',
    value: 'low',
    rarity: 'common',
    effects: [{ type: 'drawField', count: 2 }],
  },
  {
    id: 'trial-blue',
    text: '덱에서 5장을 필드에 펼친다 — 겹치면 그 자리에서 터진다',
    tone: 'gamble',
    axis: 'draw',
    dir: 'now',
    value: 'low',
    rarity: 'common',
    effects: [{ type: 'drawField', count: 5 }],
  },
  {
    id: 'beast-den-blue',
    text: '저주 2장을 지운다',
    tone: 'safe',
    axis: 'deck',
    dir: 'future',
    value: 'high',
    rarity: 'rare',
    effects: [{ type: 'removeKind', kind: 'curse', count: 2 }],
  },
  {
    id: 'ferry-red',
    text: '덱에서 1장만 필드에 펼친다 — 겹치면 그 자리에서 터진다',
    tone: 'sure',
    axis: 'draw',
    dir: 'now',
    value: 'low',
    rarity: 'common',
    effects: [{ type: 'drawField', count: 1 }],
  },
  {
    id: 'ferry-blue',
    text: '보상 2장을 내주고 저주 2장을 떠넘긴다',
    tone: 'safe',
    axis: 'deck',
    dir: 'future',
    value: 'high',
    rarity: 'rare',
    effects: [{ type: 'removeKind', kind: 'reward', count: 2 }, { type: 'removeKind', kind: 'curse', count: 2 }],
  },
  {
    id: 'crucible-red',
    text: '덱에서 6장을 필드에 펼친다 — 겹치면 그 자리에서 터진다',
    tone: 'gamble',
    axis: 'draw',
    dir: 'now',
    value: 'low',
    rarity: 'common',
    effects: [{ type: 'drawField', count: 6 }],
  },
  {
    id: 'crucible-blue',
    text: '저주 1장을 지우고 값싼 2장을 버린다',
    tone: 'safe',
    axis: 'deck',
    dir: 'future',
    value: 'low',
    rarity: 'common',
    effects: [{ type: 'removeKind', kind: 'curse', count: 1 }, { type: 'removeExtreme', end: 'lowest', count: 2 }],
  },
  {
    id: 'oracle-blue',
    text: '보상 1장, 저주 1장, 값싼 2장을 흘린다',
    tone: 'safe',
    axis: 'deck',
    dir: 'future',
    value: 'low',
    rarity: 'common',
    effects: [{ type: 'addRandom', kind: 'reward', count: 1 }, { type: 'addRandom', kind: 'curse', count: 1 }, { type: 'removeExtreme', end: 'lowest', count: 2 }],
  },
  {
    id: 'vigil-red',
    text: '덱에서 3장을 필드에 펼치고 체력 +2',
    tone: 'sure',
    axis: 'draw',
    dir: 'now',
    value: 'low',
    rarity: 'common',
    effects: [{ type: 'drawField', count: 3 }, { type: 'heal', amount: 2 }],
  },
  {
    id: 'vigil-blue',
    text: '저주 1장을 지우고 보상 1장을 잃는다',
    tone: 'safe',
    axis: 'deck',
    dir: 'future',
    value: 'low',
    rarity: 'common',
    effects: [{ type: 'removeKind', kind: 'curse', count: 1 }, { type: 'removeKind', kind: 'reward', count: 1 }],
  },
  {
    id: 'gauntlet-red',
    text: '파편 1을 캔다 — 저주 2장, 덱에서 3장이 필드에 쏟아진다',
    tone: 'now',
    axis: 'draw',
    dir: 'now',
    value: 'high',
    rarity: 'ultra',
    effects: [{ type: 'shard', count: 1 }, { type: 'addRandom', kind: 'curse', count: 2 }, { type: 'drawField', count: 3 }],
  },
  {
    id: 'gauntlet-blue',
    text: '저주 2장을 지우고 값싼 1장을 버린다',
    tone: 'later',
    axis: 'deck',
    dir: 'future',
    value: 'high',
    rarity: 'rare',
    effects: [{ type: 'removeKind', kind: 'curse', count: 2 }, { type: 'removeExtreme', end: 'lowest', count: 1 }],
  },
  {
    id: 'draw-well-blue',
    text: '필드의 저주 1장을 없앤다',
    tone: 'safe',
    axis: 'field',
    dir: 'now',
    value: 'low',
    rarity: 'common',
    effects: [{ type: 'purgeCurse', count: 1 }],
  },
  {
    id: 'gamble-draw-red',
    text: '멈출 때까지 한 장씩 뽑는다 — 저주가 겹치면 즉시 중단',
    tone: 'gamble',
    axis: 'draw',
    dir: 'now',
    value: 'low',
    rarity: 'common',
    effects: [{ type: 'pushLuck' }],
  },
  {
    id: 'gamble-draw-blue',
    text: '덱에서 1장을 펼치고 체력 +2',
    tone: 'safe',
    axis: 'draw',
    dir: 'now',
    value: 'low',
    rarity: 'common',
    effects: [{ type: 'drawField', count: 1 }, { type: 'heal', amount: 2 }],
  },
  {
    id: 'scout-red',
    text: '덱 위 3장을 확인하고 1장만 가져온다',
    tone: 'sure',
    axis: 'draw',
    dir: 'now',
    value: 'low',
    rarity: 'common',
    effects: [{ type: 'peek', count: 3, keep: 1 }],
  },
  {
    id: 'scout-blue',
    text: '눈을 감고 2장을 집는다 — 뭐가 올지 모른다',
    tone: 'gamble',
    axis: 'draw',
    dir: 'now',
    value: 'low',
    rarity: 'common',
    effects: [{ type: 'drawField', count: 2 }],
  },
  {
    id: 'shed-red',
    text: '필드의 저주 1장을 버린다',
    tone: 'safe',
    axis: 'field',
    dir: 'now',
    value: 'low',
    rarity: 'common',
    effects: [{ type: 'purgeCurse', count: 1 }],
  },
  {
    id: 'shed-blue',
    text: '필드에서 무작위로 3장을 쓸어낸다 — 무엇이 걸릴지는 모른다',
    tone: 'gamble',
    axis: 'field',
    dir: 'now',
    value: 'mid',
    rarity: 'uncommon',
    effects: [{ type: 'purgeRandom', count: 3 }],
  },
  {
    id: 'bloodletting-red',
    text: '필드의 저주 2장을 태운다 — 체력 -3',
    tone: 'sure',
    axis: 'field',
    dir: 'now',
    value: 'high',
    rarity: 'rare',
    effects: [{ type: 'purgeCurse', count: 2 }, { type: 'damage', amount: 3 }],
  },
  {
    id: 'bloodletting-blue',
    text: '덱의 저주 1장을 지우고 보상 1장을 잃는다',
    tone: 'later',
    axis: 'deck',
    dir: 'future',
    value: 'low',
    rarity: 'common',
    effects: [{ type: 'removeKind', kind: 'curse', count: 1 }, { type: 'removeKind', kind: 'reward', count: 1 }],
  },
  {
    id: 'exorcism-red',
    text: '필드의 파멸을 전부 버린다 — 체력 -2',
    tone: 'safe',
    axis: 'field',
    dir: 'now',
    value: 'high',
    rarity: 'ultra',
    effects: [{ type: 'purgeCurse', count: 9, curseType: 'doom' }, { type: 'damage', amount: 2 }],
  },
  {
    id: 'exorcism-blue',
    text: '필드의 부패를 전부 버린다 — 저주 1장을 덱에 받는다',
    tone: 'sure',
    axis: 'field',
    dir: 'now',
    value: 'high',
    rarity: 'ultra',
    effects: [{ type: 'purgeCurse', count: 9, curseType: 'rot' }, { type: 'addRandom', kind: 'curse', count: 1 }],
  },
  {
    id: 'clean-slate-red',
    text: '필드를 통째로 쓸어낸다 — 보상까지 전부 사라진다',
    tone: 'gamble',
    axis: 'field',
    dir: 'now',
    value: 'high',
    rarity: 'ultra',
    effects: [{ type: 'purgeAll' }],
  },
  {
    id: 'clean-slate-blue',
    text: '필드의 저주 1장을 버리고 값싼 2장을 덱에서 정리한다',
    tone: 'sure',
    axis: 'field',
    dir: 'now',
    value: 'low',
    rarity: 'common',
    effects: [{ type: 'purgeCurse', count: 1 }, { type: 'removeExtreme', end: 'lowest', count: 2 }],
  },
  {
    id: 'hoarder-red',
    text: '필드에 저주가 3장 이상이면 보상 3장, 아니면 저주 1장',
    tone: 'gamble',
    axis: 'deck',
    dir: 'future',
    value: 'high',
    rarity: 'rare',
    effects: [{ type: 'ifField', when: { type: 'fieldCurseAtLeast', n: 3 }, then: [{ type: 'addRandom', kind: 'reward', count: 3 }], otherwise: [{ type: 'addRandom', kind: 'curse', count: 1 }] }],
  },
  {
    id: 'hoarder-blue',
    text: '필드의 저주 1장을 버리고 보상 1장을 잃는다',
    tone: 'safe',
    axis: 'field',
    dir: 'now',
    value: 'low',
    rarity: 'common',
    effects: [{ type: 'purgeCurse', count: 1 }, { type: 'removeKind', kind: 'reward', count: 1 }],
  },
  {
    id: 'rest-red',
    text: '필드 1장당 체력 +1',
    tone: 'safe',
    axis: 'hp',
    dir: 'now',
    value: 'low',
    rarity: 'common',
    effects: [{ type: 'healPerFieldCard', amount: 1 }],
  },
  {
    id: 'rest-blue',
    text: '덱에서 2장을 손에 넣는다',
    tone: 'greed',
    axis: 'draw',
    dir: 'now',
    value: 'low',
    rarity: 'common',
    effects: [{ type: 'drawField', count: 2 }],
  },
  {
    id: 'overload-red',
    text: '필드가 7장 이상이면 저주 2장을 버린다, 아니면 2장을 더 뽑는다',
    tone: 'sure',
    axis: 'draw',
    dir: 'now',
    value: 'high',
    rarity: 'rare',
    effects: [{ type: 'ifField', when: { type: 'fieldSizeAtLeast', n: 7 }, then: [{ type: 'purgeCurse', count: 2 }], otherwise: [{ type: 'drawField', count: 2 }] }],
  },
  {
    id: 'overload-blue',
    text: '보상 2장을 덱에 넣고 체력 -4',
    tone: 'greed',
    axis: 'deck',
    dir: 'future',
    value: 'mid',
    rarity: 'uncommon',
    effects: [{ type: 'addRandom', kind: 'reward', count: 2 }, { type: 'damage', amount: 4 }],
  },
  {
    id: 'empty-hands-red',
    text: '필드가 3장 이하면 파편 1, 아니면 저주 1장',
    tone: 'now',
    axis: 'deck',
    dir: 'future',
    value: 'high',
    rarity: 'ultra',
    effects: [{ type: 'ifField', when: { type: 'fieldSizeAtMost', n: 3 }, then: [{ type: 'shard', count: 1 }, { type: 'addRandom', kind: 'curse', count: 1 }], otherwise: [{ type: 'addRandom', kind: 'curse', count: 1 }] }],
  },
  {
    id: 'empty-hands-blue',
    text: '필드의 저주 1장을 버리고 체력 -1',
    tone: 'later',
    axis: 'field',
    dir: 'now',
    value: 'low',
    rarity: 'common',
    effects: [{ type: 'purgeCurse', count: 1 }, { type: 'damage', amount: 1 }],
  },
  {
    id: 'first-step-red',
    text: '덱에서 3장을 한 번에 펼친다',
    tone: 'greed',
    axis: 'draw',
    dir: 'now',
    value: 'low',
    rarity: 'common',
    effects: [{ type: 'drawField', count: 3 }],
  },
  {
    id: 'first-step-blue',
    text: '덱에서 1장만 조심스럽게 펼친다 — 체력 +2',
    tone: 'safe',
    axis: 'draw',
    dir: 'now',
    value: 'low',
    rarity: 'common',
    effects: [{ type: 'drawField', count: 1 }, { type: 'heal', amount: 2 }],
  },
  {
    id: 'lantern-red',
    text: '덱 위 4장을 보고 2장을 골라 펼친다',
    tone: 'sure',
    axis: 'draw',
    dir: 'now',
    value: 'low',
    rarity: 'common',
    effects: [{ type: 'peek', count: 4, keep: 2 }],
  },
  {
    id: 'lantern-blue',
    text: '눈을 감고 2장을 펼친다 — 체력 +3',
    tone: 'gamble',
    axis: 'draw',
    dir: 'now',
    value: 'mid',
    rarity: 'uncommon',
    effects: [{ type: 'drawField', count: 2 }, { type: 'heal', amount: 3 }],
  },
  {
    id: 'floodgate-red',
    text: '덱에서 4장을 펼친다 — 겹치면 그 자리에서 터진다',
    tone: 'greed',
    axis: 'draw',
    dir: 'now',
    value: 'low',
    rarity: 'common',
    effects: [{ type: 'drawField', count: 4 }],
  },
  {
    id: 'floodgate-blue',
    text: '덱의 저주 2장을 없앤다',
    tone: 'later',
    axis: 'deck',
    dir: 'future',
    value: 'high',
    rarity: 'rare',
    effects: [{ type: 'removeKind', kind: 'curse', count: 2 }],
  },
  {
    id: 'sweep-red',
    text: '필드의 저주 2장을 없앤다',
    tone: 'safe',
    axis: 'field',
    dir: 'now',
    value: 'high',
    rarity: 'rare',
    effects: [{ type: 'purgeCurse', count: 2 }],
  },
  {
    id: 'sweep-blue',
    text: '필드에서 무작위 2장을 없앤다 — 보상이 걸릴 수도 있다',
    tone: 'gamble',
    axis: 'field',
    dir: 'now',
    value: 'low',
    rarity: 'common',
    effects: [{ type: 'purgeRandom', count: 2 }],
  },
  {
    id: 'salt-circle-red',
    text: '필드의 파멸을 전부 없앤다 — 체력 -3',
    tone: 'safe',
    axis: 'field',
    dir: 'now',
    value: 'high',
    rarity: 'ultra',
    effects: [{ type: 'purgeCurse', count: 9, curseType: 'doom' }, { type: 'damage', amount: 3 }],
  },
  {
    id: 'salt-circle-blue',
    text: '필드의 부패를 전부 없앤다 — 덱에 저주 1장',
    tone: 'sure',
    axis: 'field',
    dir: 'now',
    value: 'high',
    rarity: 'ultra',
    effects: [{ type: 'purgeCurse', count: 9, curseType: 'rot' }, { type: 'addRandom', kind: 'curse', count: 1 }],
  },
  {
    id: 'burn-it-red',
    text: '필드를 통째로 태운다 — 보상까지 전부 사라진다',
    tone: 'gamble',
    axis: 'field',
    dir: 'now',
    value: 'high',
    rarity: 'ultra',
    effects: [{ type: 'purgeAll' }],
  },
  {
    id: 'burn-it-blue',
    text: '저주 1장만 골라 태운다 — 체력 -2',
    tone: 'sure',
    axis: 'field',
    dir: 'now',
    value: 'low',
    rarity: 'common',
    effects: [{ type: 'purgeCurse', count: 1 }, { type: 'damage', amount: 2 }],
  },
  {
    id: 'tithe-red',
    text: '필드의 저주 3장을 없앤다 — 덱의 보상 2장을 잃는다',
    tone: 'sure',
    axis: 'field',
    dir: 'now',
    value: 'high',
    rarity: 'rare',
    effects: [{ type: 'purgeCurse', count: 3 }, { type: 'removeKind', kind: 'reward', count: 2 }],
  },
  {
    id: 'tithe-blue',
    text: '덱에서 2장을 펼친다',
    tone: 'greed',
    axis: 'draw',
    dir: 'now',
    value: 'low',
    rarity: 'common',
    effects: [{ type: 'drawField', count: 2 }],
  },
  {
    id: 'weigher-red',
    text: '필드에 저주가 3장 이상이면 파편 1, 아니면 저주 2장',
    tone: 'gamble',
    axis: 'deck',
    dir: 'future',
    value: 'high',
    rarity: 'ultra',
    effects: [{ type: 'ifField', when: { type: 'fieldCurseAtLeast', n: 3 }, then: [{ type: 'shard', count: 1 }, { type: 'addRandom', kind: 'curse', count: 1 }], otherwise: [{ type: 'addRandom', kind: 'curse', count: 2 }] }],
  },
  {
    id: 'weigher-blue',
    text: '필드의 저주 1장을 없애고 체력 -2',
    tone: 'safe',
    axis: 'field',
    dir: 'now',
    value: 'low',
    rarity: 'common',
    effects: [{ type: 'purgeCurse', count: 1 }, { type: 'damage', amount: 2 }],
  },
  {
    id: 'tally-blue',
    text: '필드가 5장 이하면 덱에서 3장을 펼친다, 아니면 저주 1장',
    tone: 'gamble',
    axis: 'draw',
    dir: 'now',
    value: 'low',
    rarity: 'common',
    effects: [{ type: 'ifField', when: { type: 'fieldSizeAtMost', n: 5 }, then: [{ type: 'drawField', count: 3 }], otherwise: [{ type: 'addRandom', kind: 'curse', count: 1 }] }],
  },
  {
    id: 'clutter-red',
    text: '필드가 8장 이상이면 무작위 4장을 쓸어낸다, 아니면 2장을 펼친다',
    tone: 'sure',
    axis: 'draw',
    dir: 'now',
    value: 'high',
    rarity: 'rare',
    effects: [{ type: 'ifField', when: { type: 'fieldSizeAtLeast', n: 8 }, then: [{ type: 'purgeRandom', count: 4 }], otherwise: [{ type: 'drawField', count: 2 }] }],
  },
  {
    id: 'clutter-blue',
    text: '체력 -3, 덱의 저주 1장을 없앤다',
    tone: 'later',
    axis: 'deck',
    dir: 'future',
    value: 'low',
    rarity: 'common',
    effects: [{ type: 'damage', amount: 3 }, { type: 'removeKind', kind: 'curse', count: 1 }],
  },
  {
    id: 'sifter-red',
    text: '필드의 저주 1장을 없애고 덱에서 1장을 펼친다',
    tone: 'sure',
    axis: 'draw',
    dir: 'now',
    value: 'low',
    rarity: 'common',
    effects: [{ type: 'purgeCurse', count: 1 }, { type: 'drawField', count: 1 }],
  },
  {
    id: 'sifter-blue',
    text: '필드에서 무작위 3장을 없앤다',
    tone: 'gamble',
    axis: 'field',
    dir: 'now',
    value: 'mid',
    rarity: 'uncommon',
    effects: [{ type: 'purgeRandom', count: 3 }],
  },
  {
    id: 'quiet-room-blue',
    text: '덱에서 2장을 펼치고 체력 +2',
    tone: 'greed',
    axis: 'draw',
    dir: 'now',
    value: 'low',
    rarity: 'common',
    effects: [{ type: 'drawField', count: 2 }, { type: 'heal', amount: 2 }],
  },
  {
    id: 'reckoning-red',
    text: '필드에 저주가 4장 이상이면 전부 없앤다, 아니면 저주 1장을 받는다',
    tone: 'gamble',
    axis: 'field',
    dir: 'now',
    value: 'high',
    rarity: 'ultra',
    effects: [{ type: 'ifField', when: { type: 'fieldCurseAtLeast', n: 4 }, then: [{ type: 'purgeCurse', count: 9 }], otherwise: [{ type: 'addRandom', kind: 'curse', count: 1 }] }],
  },

  /* ---------- 위기 전용: 둘 다 손해이고 덜 나쁜 쪽을 고른다 ---------- */

  {
    id: 'crisis-blood',
    text: '피로 값을 치른다 — 체력 -4',
    tone: 'sure',
    axis: 'hp',
    dir: 'now',
    value: 'low',
    rarity: 'common',
    crisis: true,
    effects: [{ type: 'damage', amount: 4 }],
  },
  {
    id: 'crisis-blood-deep',
    text: '더 깊이 벤다 — 체력 -7',
    tone: 'gamble',
    axis: 'hp',
    dir: 'now',
    value: 'low',
    rarity: 'uncommon',
    crisis: true,
    effects: [{ type: 'damage', amount: 7 }],
  },
  {
    id: 'crisis-taint',
    text: '덱에 저주 3장을 받는다',
    tone: 'later',
    axis: 'deck',
    dir: 'future',
    value: 'low',
    rarity: 'common',
    crisis: true,
    effects: [{ type: 'addRandom', kind: 'curse', count: 3 }],
  },
  {
    id: 'crisis-taint-heavy',
    text: '덱에 저주 5장을 받는다',
    tone: 'later',
    axis: 'deck',
    dir: 'future',
    value: 'low',
    rarity: 'uncommon',
    crisis: true,
    effects: [{ type: 'addRandom', kind: 'curse', count: 5 }],
  },
  {
    id: 'crisis-strip',
    text: '값나가는 2장을 뺏긴다',
    tone: 'now',
    axis: 'deck',
    dir: 'future',
    value: 'low',
    rarity: 'common',
    crisis: true,
    effects: [{ type: 'removeExtreme', end: 'highest', count: 2 }],
  },
  {
    id: 'crisis-strip-rewards',
    text: '덱의 보상 3장을 잃는다',
    tone: 'now',
    axis: 'deck',
    dir: 'future',
    value: 'low',
    rarity: 'common',
    crisis: true,
    effects: [{ type: 'removeKind', kind: 'reward', count: 3 }],
  },
  {
    id: 'crisis-spill',
    text: '덱에서 3장이 필드로 쏟아진다 — 겹치면 그 자리에서 터진다',
    tone: 'gamble',
    axis: 'draw',
    dir: 'now',
    value: 'low',
    rarity: 'common',
    crisis: true,
    effects: [{ type: 'drawField', count: 3 }],
  },
  {
    id: 'crisis-rot',
    text: '중립 2장이 저주로 삭는다',
    tone: 'later',
    axis: 'deck',
    dir: 'future',
    value: 'low',
    rarity: 'common',
    crisis: true,
    effects: [{ type: 'transform', from: 'neutral', to: 'curse', count: 2 }],
  },
  {
    id: 'crisis-bleed-taint',
    text: '체력 -2, 덱에 저주 2장',
    tone: 'sure',
    axis: 'hp',
    dir: 'now',
    value: 'low',
    rarity: 'common',
    crisis: true,
    effects: [{ type: 'damage', amount: 2 }, { type: 'addRandom', kind: 'curse', count: 2 }],
  },
  {
    id: 'crisis-toll',
    text: '체력 -3, 값싼 3장을 잃는다',
    tone: 'safe',
    axis: 'hp',
    dir: 'now',
    value: 'low',
    rarity: 'common',
    crisis: true,
    effects: [{ type: 'damage', amount: 3 }, { type: 'removeExtreme', end: 'lowest', count: 3 }],
  },
];
